In [21]:
import pandas as pd
import os
import sys

project_root = os.path.dirname(os.getcwd())
print(project_root)
df = pd.read_parquet(os.path.join(project_root, 'lead_lag_matrices.parquet'))
print(df)

/Users/evanheus/Desktop/AFP
                     timestamp method stock1 stock2     value
0    2024-11-29 09:35:00-05:00     C1   AAPL   AAPL  0.000000
1    2024-11-29 09:35:00-05:00     C1   AAPL   TSLA  0.072921
2    2024-11-29 09:35:00-05:00     C1   AAPL   AMZN -1.000000
3    2024-11-29 09:35:00-05:00     C1   AAPL    SPY -1.000000
4    2024-11-29 09:35:00-05:00     C1   TSLA   AAPL -0.072921
...                        ...    ...    ...    ...       ...
6171 2024-11-29 16:00:00-05:00     C1   AMZN    SPY -1.000000
6172 2024-11-29 16:00:00-05:00     C1    SPY   AAPL  0.608287
6173 2024-11-29 16:00:00-05:00     C1    SPY   TSLA  1.000000
6174 2024-11-29 16:00:00-05:00     C1    SPY   AMZN  1.000000
6175 2024-11-29 16:00:00-05:00     C1    SPY    SPY  0.000000

[6176 rows x 5 columns]

In [22]:
df[df['timestamp']== '2024-11-29 10:00:00-05:00']

                    timestamp method stock1 stock2     value
400 2024-11-29 10:00:00-05:00     C1   AAPL   AAPL  0.000000
401 2024-11-29 10:00:00-05:00     C1   AAPL   TSLA  0.838771
402 2024-11-29 10:00:00-05:00     C1   AAPL   AMZN -1.000000
403 2024-11-29 10:00:00-05:00     C1   AAPL    SPY -1.000000
404 2024-11-29 10:00:00-05:00     C1   TSLA   AAPL -0.838771
405 2024-11-29 10:00:00-05:00     C1   TSLA   TSLA  0.000000
406 2024-11-29 10:00:00-05:00     C1   TSLA   AMZN  0.184386
407 2024-11-29 10:00:00-05:00     C1   TSLA    SPY  0.221852
408 2024-11-29 10:00:00-05:00     C1   AMZN   AAPL  1.000000
409 2024-11-29 10:00:00-05:00     C1   AMZN   TSLA -0.184386
410 2024-11-29 10:00:00-05:00     C1   AMZN   AMZN  0.000000
411 2024-11-29 10:00:00-05:00     C1   AMZN    SPY -1.000000
412 2024-11-29 10:00:00-05:00     C1    SPY   AAPL  1.000000
413 2024-11-29 10:00:00-05:00     C1    SPY   TSLA -0.221852
414 2024-11-29 10:00:00-05:00     C1    SPY   AMZN  1.000000
415 2024-11-29 10:00:00-05:00     C1    SPY    SPY  0.000000